### ISSUE TITLE
unable to Forgot password /reset password

### ISSUE THREAD

**Issue by thebeatlesteam2** [krishna2614/The-Beatles#14]
we are unable to reset the password using forget /reset password. It can be caused by not implementing properly or issues with the email server.

**Comment by YamunaDorsala** [comment]
<img width="960" alt="Screenshot 2023-10-26 194111" src="https://github.com/krishna2614/The-Beatles/assets/149100654/e877de43-1c31-4f28-9bc8-ef726ec3df79">
<img width="960" alt="Screenshot 2023-10-26 194129" src="https://github.com/krishna2614/The-Beatles/assets/149100654/e956435b-aea3-4c9a-9c1d-49191122d2ac">
<img width="960" alt="Screenshot 2023-10-26 194154" src="https://github.com/krishna2614/The-Beatles/assets/149100654/bc8b8707-812f-4248-b623-83c318f0eb7a">
<img width="960" alt="Screenshot 2023-10-26 194203" src="https://github.com/krishna2614/The-Beatles/assets/149100654/f7c449f2-11cb-4e88-9719-2d790e598519">
Issue is fixed.
